name: task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Mobx
  mobx: 1.1.1
  flutter_mobx: 1.1.0
  provider: 4.0.4
  rxdart: 0.23.1

  #Icons
  cupertino_icons: ^0.1.3

  #Shared
  shared_preferences: ^0.5.6

  #Bot Toast
  bot_toast: ^2.3.1

  flutter_masked_text: 0.8.0
  intl: 0.16.1

  flutter_slidable: "^0.5.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Mobx dev
  build_runner: 1.9.0
  mobx_codegen: 1.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-VariableFont_slnt,wght.ttf