name: task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Mobx
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4
  provider: ^6.0.4
  rxdart: ^0.27.5

  #Icons
  cupertino_icons: ^1.0.5

  #Shared
  shared_preferences: ^2.0.15

  #Bot Toast
  bot_toast: ^4.0.3

  flutter_masked_text: 0.8.0
  intl: ^0.17.0

  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Mobx dev
  build_runner: ^2.3.2
  mobx_codegen: ^2.0.7+3

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-VariableFont_slnt,wght.ttf